### ISSUE TITLE
Do you know about general purpose cyrillic automatic inflectors (stands not for names only)

### ISSUE THREAD

**Issue by a-x-** [petrovich/petrovich-js#12]

**Comment by dustalov** [comment]
Generally, this is a morphological analysis and synthesis task. Consider the corresponding NLPub article: [https://nlpub.ru/Обработка_текста#Морфологический анализ](https://nlpub.ru/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0#.D0.9C.D0.BE.D1.80.D1.84.D0.BE.D0.BB.D0.BE.D0.B3.D0.B8.D1.87.D0.B5.D1.81.D0.BA.D0.B8.D0.B9_.D0.B0.D0.BD.D0.B0.D0.BB.D0.B8.D0.B7) (in Russian).

**Comment by mikhail-barg** [comment]
I'm using Pymorphy2 (https://github.com/kmike/pymorphy2)

**Comment by a-x-** [comment]
Thank you,
great list
